// lit/lib/exercises/lists-and-arrays.js
import { LitElement, html } from "lit";

export class ListsAndArrays extends LitElement {

    static properties = {
        numbers: { type: Array }
    }

    constructor() {
        super();

        this.numbers = [...new Array(5)].map(() => Math.floor(Math.random() * 20));
        console.log(this.numbers);

        this.languages = [
            { name: "Javascript", short: "JS" },
            { name: "Typescript", short: "TS" },
            { name: "Java", short: "Java" },
            { name: "Python", short: "Py" },
        ]

        this.languageList = this.languages.map(lang => (
            html`<li>${lang.name} (${lang.short})</li>`
        ));
    }

    randomizeNumbers() {
        this.numbers = [...new Array(Math.floor(Math.random() * 10))].map(() => Math.floor(Math.random() * 20));
    }

    render() {
        console.log(this.languageList);
        return html`
            <h3>Lists and Arrays</h3>

            <button .numbers=${this.numbers} @click=${this.randomizeNumbers}>So random</button>

            <ul>
                ${this.languageList}
            </ul>

            <ul>
                ${this.numbers.map(num => html`
                    <li>${num}</li>
                `)}
            </ul>

        `;
    }
}

customElements.define("lists-and-arrays", ListsAndArrays);

// react/src/exercises/ListsAndArrays.jsx
import React from "react";

export function ListsAndArrays() {

    const numbers = [...new Array(5)].map(() => Math.floor(Math.random() * 20));
    console.log(numbers);

    const languages = [
        { name: "Javascript", short: "JS" },
        { name: "Typescript", short: "TS" },
        { name: "Java", short: "Java" },
        { name: "Python", short: "Py" },
    ]

    const languageList = languages.map(lang => (
        <li key={lang.short}>{lang.name} ({lang.short})</li>
    ));

    return (
        <div>
            <h3>Lists And Arrays</h3> 

            <p>Numbers: </p>
            <ul>
                {numbers.map(num => <li key={num}>{num}</li>)}
            </ul>

            <ul>
                {languageList}
            </ul>
        </div>
    )
}
