// react/src/exercises/ConditionalRendering.jsx
import React, { useState } from "react";

export function ConditionalRendering() {
    const [count, setCount] = useState(0);

    function increment() {
        setCount(count + 1);
    }

    let countMessage = <></>;
    if (count > 10) {
        countMessage = <p>Wow, that's over ten!</p>;
    }

    function renderMessage() {
        if (count <= 10) return;
        return <p>Wow, that's over ten!</p>;
    }

    return (
        <div>
            <h3>Conditional rendering</h3>
            <p>Count: {count}</p>

            {countMessage}

            {count > 10 && <p>Wow, that's over ten!</p>}

            {count > 10 ? <p>Wow, that's over ten!</p> : <></>}

            {renderMessage()}
            
            <button onClick={increment}>Increment</button>
        </div>
    )
}

// lit/lib/exercises/conditional-rendering.js
import { LitElement, html } from "lit";
import { when } from "lit/directives/when.js";

export class ConditionalRendering extends LitElement {

    renderMessage() {
        if (false) return html``;
        return html`<p>Wow, that's over ten!</p>`;
    }

    render() {
        const count = 10;

        let countMessage = html``;
        if (count > 10) {
            countMessage = html`<p>Wow, that's over ten!</p>`;
        }

        return html`
            <h3>Conditional Rendering</h3>

            ${countMessage}

            ${count > 10 && html`<p>Wow, that's over ten!</p>`}

            ${when(count > 10, () => html`<p>Wow, that's over ten!</p>`)}

            ${count > 10 ? html`<p>Wow, that's over ten!</p>` : html``}

            ${count > 10 ? html`<p>Wow, that's over ten!</p>` : ''}

            ${count > 10 ? html`<p>Wow, that's over ten!</p>` : undefined}

            ${count > 10 ? html`<p>Wow, that's over ten!</p>` : null}

            ${this.renderMessage()}

        `;
    }
}

customElements.define("conditional-rendering", ConditionalRendering);
